---

# Disable restart on crash
- name: Ensure automatic restart is disabled after crash
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl
    name: AutoReboot
    type: dword
    data: 0
    state: present
